language: python
python: 3.7

jobs:
  include:
    - if: branch = master
      python: 3.7
      env: TOXENV=py37-master
      after_success: codecov
    - if: branch != master
      python: 3.7
      env: TOXENV=py37-dev
      after_success: codecov
    - env: TOXENV=build
      python: 3.7
    - env: TOXENV=pre-commit
      python: 3.7
      dist: xenial
    - stage: Deploy to Test PyPI release
      env: TOXENV=build
      before_script: sed -i -E "s/^([0-9]+\.[0-9]+\.[0-9]+)$/\1.$TRAVIS_BUILD_NUMBER/" version.txt
      deploy:
        distributions: skip
        skip_cleanup: true
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: "__token__"
        password:
          secure: "EawxYmHVTFuA6EeAhLjErtmR+eoVxYeg0Kn3vzW4PLnodfqgjC1LjM3o3dF8evYFJOFCZ1GWyxDGFgnjztkpyNhWYJuJlyP/Y2ExQ3JuKk2+7qKXgEhZqd4aCzCVIxK31MSRHLZ4XeJZEehFe9EgINz1pUh0sHtQeaUc6QoalcEKGBbhYNpmuY6Tu5gmo2RFcike2pT+McB5KkYjHoL0yjxiU9C33j4CIhbfC1KxazQTRPEzqcJVRP4YkGRB6lTsJdRJk+iNf3EJ4RQXKPOQ7bz5osh5ZVzTZJpqsvcTNkELF0nA9ZQWY3Ajl1GAys3Z5Dq/95hJVhdWF6GYxAESp8uIBfZzNSZs+DFOtTs8qkBZZtfpdsqX7ywt6U1mfAjlTlj4lTwip/ToXKAe/e1svHiI7qa8/6Ol2BDJX+/jVKprEkHdNlAIIgJqNPqBVxlMyRvsU99SVpeT9/KuKL8Wumaha/HPKK6OeBCTLbSEo1wS4YWaQdPzJI5OfDlG/dDzIH9Mx5aelT8VgPrKQCscbzd9NOgxApSMc7Lb6vAfCw3VLanWTxSQlKk7U+hMFBeytTLTAFMDp59M8s/yatYsLIp83v/bAE4gsUq7zEi+53DvgUxstYZqRMABsBqhor1uHWSaBNkfvsjjbV35cBsO4sCjv49QXdEuMDx4d75KJIM="
        on:
          branch: dev
    - stage: Deploy to PyPI release
      env: TOXENV=build
      deploy:
        distributions: skip
        skip_cleanup: true
        provider: pypi
        user: "__token__"
        password:
          secure: "poXCtVYJNfG0qL4DnY8AFWxWmibIA4gd/7lEEB7Kfy19Qvy6PN1KC5ptb0x75lMUN48tlzilA+tqKBs6bg9PiEX1AjkJbwcoWS7FgQFDhCqlt/d5oH5mYqcTTKHlssgph3CJevSGZCeyWSNMKK0ssMTnw6CCt0X5en13kxPWtd3H83dPLcJ4ED4jymQUE5ASt6NODuAJPHfeuqhyqAvC7jnANRAO2GWCNWOMoWeFJv/AXeoMP68SOhGcvn4JRB36AapB/ptNJYD+nGcwljy1uHYX76aK7FEZFGi71mZnx3cObmzTEFA/E9+GBhUVu+9PY6PzKJpaY4yhN3wQmwlU2Rad0bqovYIDLQsFdCFPYRzSaydUakCp99/WhT170wiJM2czuT1+RF3o9iaNTMsH0D2F/c6R3e5Je1MbzhrH3gxIWhVfA9qUejABzccb4eLc6defwhAnVfu96BM1CiZ6TQTinLvPk2skgtlS65zRA/VIiSv9C1uyS8dDlRK7T7K1gKdQbuLPW2fZLSEU6VSqsariefjtXrNm7dB4A/71DpFhNd0yieXorqTUZXJMyRBIA7N9txH08Gl2GezClW/kDavR/g97EmCeAZv39XOE9R2QE9sgvyjp8Oil3h48rYiONtQiHGEamq/hbdeANybILzFl2cjp2fOZxIYZOqlwWdU="
        on:
          tags: true
    - stage: Create GitHub release
      env: TOXENV=build
      before_deploy:
        - export AUTHOR_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
        - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
        - export GIT_TAG="$(cat version.txt | tr -d ' \t\n\r')"
        - git config --local user.name $AUTHOR_NAME
        - git config --local user.email $AUTHOR_EMAIL
        - git tag $GIT_TAG
      deploy:
        provider: releases
        skip_cleanup: true
        draft: true
        api_key:
          secure: "xbxawMXTpNjQj8Z/LrVFW9iCNtfnSjw61DeMpVrKURP9kvqxVmu2Cj+pAf992LQcYYUr7BPKTxT5IxEGZdo0KDmW+/UfQCqH4hRL32BMkfVKkEuN62Pb6OpxEqqvvhkoDddCZ2ueLrihNag9jdtDvOxzYWEe3d07lVDatghtS0Fv7tXfMFlrrqDdo8exWolT9+iyd28UwWco1jKuQHQDThkHZA0x5ymFA6SC9Sse38ejItMNfDWKurGxy7DcdlBAKcGO1Cw0DpmJTNW+/oc6OL54BQf6/8keCrkF2ZQ1928NGrpw/JsMyuWOKh838Uk57XM2p+xma+NI+9vatQ8ZisifB5NLFicRHZa5fj6wmtBmlKthxdYfFXUU1/5uGRSQ7JqqrHqVL92olJi4pC3/IEFT7ER4aEtDf/zxNl9zhs9v+d06iboGianiFDdDT88DcQXtjWsVmodtGgLH/wZanFxSo5YYsKZLeci0Z5rnhtLJgl16fd2RRrOhsrRO/0eThr3akUsG9tH+VcLC1nC98Qx5nELItC1TqF/Uxe4Rwz+npzh+t7VgLQCYQ1RLuX3JcRtnSO5P+g7cbifjTQzQzxyby+VVsZvfqCjqLZD+gpE6ffv9rm+lGXQPsqOSjqbfzET+hGaAvIpfu95lAXMyDoAFZHdYgvDEEJjTpJBZJ/s="
        file_glob: true
        file: dist/*
        name: cloudshell-cp-azure $GIT_TAG
        target_commitish: master
        on:
          branch: master
    - stage: Check version
      language: bash
      install:
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout -qf $TRAVIS_PULL_REQUEST_BRANCH
      script: "! git diff --exit-code --quiet origin/master version.txt"

install:
  - pip install tox
  - pip install codecov

script: tox

stages:
  - name: Check version
    if: branch = master AND type = pull_request
  - name: Test
  - name: Deploy to Test PyPI release
    if: branch = dev AND type != pull_request
  - name: Create GitHub release
    if: branch = master AND type != pull_request
  - name: Deploy to PyPI release
    if: tag IS present